### ISSUE TITLE
Asset Inventory tool : Installation issues (json & missing dependencies)

### ISSUE THREAD

**Issue by varelasavela** [GoogleCloudPlatform/professional-services#240]
Hi guys

I  ran into some issues during your installation instructions for Asset Inventory tool :

-  in the config.yaml file there is the key "import_pipeline_runtime_environment" with not valid json value. After I fixed it the issue has gone.
-  there is missing dependency in your requirements.txt file - "requests-futures"

Thx
Evgeny

**Comment by bmenasha** [comment]
> there is missing dependency in your requirements.txt file - "requests-futures"

This is mentioned in the setup.py. I expect it to be enough as described here: 

https://packaging.python.org/discussions/install-requires-vs-requirements/

Since setup.py is a subset of what's needed, with requirements.txt listing optional packages. Do you think I'm not doing this correctly? 
thanks

> in the config.yaml file there is the key "import_pipeline_runtime_environment" with not valid json value. After I fixed it the issue has gone.

Thanks. I think this will fix it: 

https://github.com/GoogleCloudPlatform/professional-services/pull/237/commits/8fc969b0da6d4f1bd9806f85f6de265eb1345dca

**Comment by varelasavela** [comment]
I missed it. May be you should add it to installation instructions
