### ISSUE TITLE
ci: should images for an asset's test be stored in gcr

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/professional-services#500]
Should we recommend that cloudbuild files to run tests push custom images to the eng council project GCR and pull / cache from them?

Should we have a TTL on how many versions of an image we keep in GCR?

CC: @prathapreddy123 @tswast @morgante 

See this [conversation](https://github.com/GoogleCloudPlatform/professional-services/pull/496#discussion_r435585480) in #496.

**Comment by tswast** [comment]
One issue with caching builds is that it can leave us without knowing if a
package update / installation is broken, as we'd only update that layer of
the image of the install steps change.

Unlike my time in DevRel, we aren't the one's publishing most of the key
dependencies, so we might consider this a good thing (less flakey builds
due to packaging)

>

**Comment by agold-rh** [comment]
Closed due to inactivity.
